/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerwaltungRouteImport } from './routes/verwaltung'
import { Route as AuthenticatedHoerbereichRouteImport } from './routes/_authenticated/hoerbereich'
import { Route as AuthenticatedTerminRouteImport } from './routes/_authenticated/termin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerwaltungRoute = VerwaltungRouteImport.update({
  id: '/verwaltung',
  path: '/verwaltung',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHoerbereichRoute =
  AuthenticatedHoerbereichRouteImport.update({
    id: '/hoerbereich',
    path: '/hoerbereich',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerminRoute = AuthenticatedTerminRouteImport.update({
  id: '/termin',
  path: '/termin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verwaltung': typeof VerwaltungRoute
  '/hoerbereich': typeof AuthenticatedHoerbereichRoute
  '/termin': typeof AuthenticatedTerminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verwaltung': typeof VerwaltungRoute
  '/hoerbereich': typeof AuthenticatedHoerbereichRoute
  '/termin': typeof AuthenticatedTerminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verwaltung': typeof VerwaltungRoute
  '/_authenticated/hoerbereich': typeof AuthenticatedHoerbereichRoute
  '/_authenticated/termin': typeof AuthenticatedTerminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/verwaltung'
    | '/hoerbereich'
    | '/termin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/verwaltung'
    | '/hoerbereich'
    | '/termin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/verwaltung'
    | '/_authenticated/hoerbereich'
    | '/_authenticated/termin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerwaltungRoute: typeof VerwaltungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verwaltung': {
      id: '/verwaltung'
      path: '/verwaltung'
      fullPath: '/verwaltung'
      preLoaderRoute: typeof VerwaltungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hoerbereich': {
      id: '/_authenticated/hoerbereich'
      path: '/hoerbereich'
      fullPath: '/hoerbereich'
      preLoaderRoute: typeof AuthenticatedHoerbereichRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/termin': {
      id: '/_authenticated/termin'
      path: '/termin'
      fullPath: '/termin'
      preLoaderRoute: typeof AuthenticatedTerminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHoerbereichRoute: typeof AuthenticatedHoerbereichRoute
  AuthenticatedTerminRoute: typeof AuthenticatedTerminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHoerbereichRoute: AuthenticatedHoerbereichRoute,
  AuthenticatedTerminRoute: AuthenticatedTerminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerwaltungRoute: VerwaltungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
